"""Deterministic RidePulse MVP baseline.

This script intentionally uses no LLM and no embedding model. It proves the
evidence contract, grouping, scoring baseline, and human-review gates without
claiming that the full target architecture is implemented.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path


SEVERITY_SCORE = {"S1": 5, "S2": 4, "S3": 3, "S4": 2, "S5": 1}


def load_records(path: Path) -> list[dict]:
    records = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "evidence_id",
        "source_type",
        "platform",
        "source_url",
        "original_text",
        "theme",
        "severity",
        "evidence_status",
    }
    seen = set()
    for row in records:
        missing = sorted(required - row.keys())
        if missing:
            raise ValueError(f"{row.get('evidence_id', '<unknown>')} missing: {missing}")
        if row["evidence_id"] in seen:
            raise ValueError(f"duplicate evidence_id: {row['evidence_id']}")
        if not row["source_url"].startswith("https://"):
            raise ValueError(f"non-HTTPS source: {row['evidence_id']}")
        if row["severity"] not in SEVERITY_SCORE:
            raise ValueError(f"invalid severity: {row['evidence_id']}")
        seen.add(row["evidence_id"])
    return records


def build_cards(records: list[dict]) -> list[dict]:
    groups: dict[str, list[dict]] = defaultdict(list)
    for row in records:
        if row["source_type"] in {"public_user_comment", "support_forum_post"}:
            groups[row["theme"]].append(row)

    cards = []
    for theme, evidence in sorted(groups.items()):
        platforms = sorted({row["platform"] for row in evidence})
        max_severity = max(SEVERITY_SCORE[row["severity"]] for row in evidence)
        has_switching = any(row["issue_type"] == "switching_intent" for row in evidence)

        score = min(100, 15 * len(evidence) + 8 * len(platforms) + 6 * max_severity + (8 if has_switching else 0))
        if len(platforms) >= 2 and len(evidence) >= 3:
            confidence = "medium"
            review_reason = "Cross-platform evidence exists; root cause still requires product validation."
        else:
            confidence = "low"
            review_reason = "Evidence is concentrated on one platform; do not generalize before adding another source."

        cards.append(
            {
                "theme": theme,
                "priority_score": score,
                "confidence": confidence,
                "evidence_ids": [row["evidence_id"] for row in evidence],
                "platforms": platforms,
                "max_severity": next(key for key, value in SEVERITY_SCORE.items() if value == max_severity),
                "human_review_required": True,
                "review_reason": review_reason,
            }
        )
    return cards


def render_markdown(cards: list[dict], records: list[dict]) -> str:
    by_id = {row["evidence_id"]: row for row in records}
    lines = [
        "# RidePulse AI MVP Evidence Cards",
        "",
        "> Generated by the deterministic baseline. No LLM or embedding result is claimed.",
        "",
    ]
    for card in cards:
        lines.extend(
            [
                f"## {card['theme']}",
                "",
                f"- Priority score: {card['priority_score']}/100",
                f"- Confidence: {card['confidence']}",
                f"- Max severity: {card['max_severity']}",
                f"- Human review required: {str(card['human_review_required']).lower()}",
                f"- Review reason: {card['review_reason']}",
                "- Evidence:",
            ]
        )
        for evidence_id in card["evidence_ids"]:
            row = by_id[evidence_id]
            lines.append(f"  - [{evidence_id}]({row['source_url']}): {row['translated_text']}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("data/verified_evidence_sample.json"))
    parser.add_argument("--output", type=Path, default=Path("output/evidence_cards.md"))
    args = parser.parse_args()

    records = load_records(args.input)
    cards = build_cards(records)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_markdown(cards, records), encoding="utf-8")
    print(f"wrote {len(cards)} card(s) from {len(records)} evidence record(s): {args.output}")


if __name__ == "__main__":
    main()

